name = "Mmp 10"
author = "marf"
version = "10.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65b7708ff4c4dabae7cb9190ea7425d1fffe184c1bcbb6365372e43b9cefec58"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
