name = "Mmp 10"
author = "marf"
version = "10.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10b1cf82b59a13f0c206da477134fdd24e590d06d7f9afd329e04e3522827ba5"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
